sudo: false
language: python
matrix:
    include:
        - python: 2.6
        - python: 2.7
        - language: generic
          os: osx
          env: PYVER=py26
        - language: generic
          os: osx
          env: PYVER=py27
install:
    - ./.ci/travis/install.sh
script:
    - ./.ci/travis/run.sh
after_success:
  - coveralls  # upload reports to coveralls.io