sudo: false
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - language: generic
      os: osx
      env: TRAVIS_PYTHON_VERSION=2.6
    - language: generic
      os: osx
      env: TRAVIS_PYTHON_VERSION=2.7

install:
    - if [[ "$(uname -s)" == 'Darwin' ]]; then ./.travis/osx-install-python.sh; fi
    - pip install coverage python-coveralls mock --quiet
    - pip install . --quiet
    - pip freeze

script:
    - if [[ "$(uname -s)" == 'Darwin' ]]; then ./.travis/osx-virtualenv.sh; fi
    - coverage run --branch `which trial` --reporter=bwverbose tests/test_agent
    - mv -v .coverage .coverage.1
    - coverage run --branch `which trial` --reporter=bwverbose tests/test_jobtypes
    - mv -v .coverage .coverage.2
    - coverage combine

after_success:
  - coveralls