language: python
python:
  - 2.5
  - 2.6
  - 2.7

install:
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then pip install unittest2 simplejson --use-mirrors ; fi
  - pip install . --use-mirrors

script:
  - pip freeze
  - nosetests -s --verbose tests
