language: python
python:
  - 2.6
  - 2.7

install:
  - mkdir $HOME/.pip/ && curl https://raw.github.com/pyfarm/pyfarm/master/misc/travis_pip.conf -o $HOME/.pip/pip.conf
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then pip install simplejson; fi
  - pip install coverage python-coveralls psutil netifaces netaddr
  - pip install git+git://github.com/pyfarm/pyfarm-core.git#egg=pyfarm.core --egg # TODO: remove dev install
  - pip install git+git://github.com/pyfarm/pyfarm-jobtypes.git#egg=pyfarm.jobtypes --egg # TODO: remove dev install
  - pip install .

script:
  - pip freeze
  - coverage run --branch `which trial` --reporter=bwverbose tests/*.py

after_success:
  - coveralls
