sudo: false
language: python
matrix:
  include:
    - python: 2.6
    - python: 2.7
    - language: generic
      os: osx
      env: TRAVIS_PYTHON_VERSION=2.6
    - language: generic
      os: osx
      env: TRAVIS_PYTHON_VERSION=2.7

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
  - coveralls