language: python
python:
  - 2.5
  - 2.6
  - 2.7

install:
  - mkdir $HOME/.pip/ && curl https://raw.github.com/pyfarm/pyfarm/master/misc/travis_pip.conf -o $HOME/.pip/pip.conf
  - if [[ $TRAVIS_PYTHON_VERSION != "2.7" ]]; then pip install unittest2; fi
  - pip install .

script:
  - pip freeze
  - nosetests -s --verbose tests
