language: python
sudo: false
python:
  - 2.6
  - 2.7

cache:
  directories:
  - $HOME/.pipcache

env:
  # TODO: test the agent against multiple configurations, independent of DB configuration.
  # NOTE: Do not use sqlite here as it breaks because of concurrency issues
  matrix:
    - PYFARM_AGENT_TEST_HTTP_SCHEME="http"
    - PYFARM_AGENT_TEST_HTTP_SCHEME="https"

matrix:
  fast_finish: true

before_install:
  - curl -o retry.sh https://raw.githubusercontent.com/pyfarm/pyfarm-build/master/travis/retry.sh
  - source retry.sh

install:
  # Agent installation
  - retry pip install coverage python-coveralls mock --quiet
  - if [[ $PYFARM_AGENT_TEST_HTTP_SCHEME == "https" ]]; then retry pip install PyOpenSSL service_identity --quiet; fi
  - retry pip install -e . --egg --quiet
  - pip freeze

script:
  - coverage run --branch `which trial` --reporter=bwverbose tests/test_agent
  - mv -v .coverage .coverage.1
  - coverage run --branch `which trial` --reporter=bwverbose tests/test_jobtypes
  - mv -v .coverage .coverage.2
  - coverage combine

after_success:
  - coveralls
