language: python
python:
  - 2.6
  - 2.7

install:
  - mkdir $HOME/.pip/ && curl https://raw.github.com/pyfarm/pyfarm/master/misc/travis_pip.conf -o $HOME/.pip/pip.conf
  - pip install coverage python-coveralls
  - pip install git+git://github.com/pyfarm/pyfarm-core.git#egg=pyfarm.core --egg # TODO: remove dev install
  - pip install .

script:
  - pip freeze
  - coverage run --branch `which trial` --reporter=bwverbose tests
#  - coverage run --branch `which trial` --reporter=bwverbose tests/test_agent
#  - mv -v .coverage .coverage.1
#  - coverage run --branch `which trial` --reporter=bwverbose tests/test_jobtypes
#  - mv -v .coverage .coverage.2
  - coverage combine

after_success:
  - coveralls
